[package]
name = "bmstu-thesis"
version = "0.1.1"
entrypoint = "src/lib.typ"
authors = ["ITesserakt <potryas85@mail.ru>"]
description = "Template for thesis using BMSTU conventions"
compiler = "0.14.0"
repositoty = "https://github.com/ITesserakt/typst-bmstu-thesis"
license = "MIT"
